.eslintrc.json
.gitignore
package-lock.json
package.json
src/auth/index.js
src/components/GoogleLoginButton.js
src/pages/Home.js

- 서비스를 이용하기 위해서는 구글 계정을 이용한 로그인이 필요합니다. 따라서 유저가 로그인을 할 수 있도록 로그인 버튼을 직접 구현하였습니다. 
- firebase 라이브러리를 설치하였고, firebase의 환경 변수가 git에 올라가면 안되므로 dotenv도 함께 설치한 뒤 .gitignore에 올렸습니다.  
- auth 폴더를 새롭게 만든 뒤 그곳에 firebase 설정을 해주는 코드를 작성하였습니다.   
- 구글 로그인 버튼이라는 컴포넌트를 만들었고, 이 버튼을 클릭하면 구글 로그인 팝업창이 뜨도록 하였습니다.  
- 또 이 버튼은 Home.js에 위치하도록 설정하였습니다. 
- 존재하지 않습니다.
- 협업 작업을 해야 하기 때문에 작업자 모두 환경변수 파일을 공통적으로 가지고 있어야 하므로 환경변수에 대한 공유 논의를 좀 해야 할 것 같습니다. 
- firebase 설정 방법이 사람마다 다르기 때문에 제가 설정한 방법이 괜찮을지 검토해주시기 바랍니다.

구글 로그인 버튼 구현

---

src/App.js
src/features/userSaga.js
src/features/userSlice.js
src/pages/Home.js

- 우리 프로그램은 redux를 이용하여 상태관리를 수행하며,   
redux에 저장되는 내용은 유저의 로그인 여부와 유저 정보가 있습니다.  
그리고 프론트 페이지의 동작은 redux의 상태에 의존하고 있습니다.   
- 새로고침이 발생할 때마다 redux 상태가 초기화되기 때문에 유저가 로그인한 사실과, 유저의 정보가 증발하는 문제점이 있어,  
새로고침을 하여도 기존의 유저 정보와 로그인 정보를 잃지 않도록 코드를 수정할 필요성이 있었습니다.
- 적절하지 않은 변수명 및 개행 스타일을 수정할 필요가 있었습니다.
-  새로고침할 때마다 App.js의 페이지가 매번 새롭게 랜더링되는데, 이때 useEffect와  firebase 라이브러리가  
기본적으로 제공하는 기능을 이용하여 새로고침 시마다 기존의 유저가 로그인한 상태였는지 파악하고, 만약 그렇다면  
액션 함수를 실행하여 기존에 로그인 한 유저 정보가 다시 redux에 저장되게끔 하였습니다. 
- 변수명을 새롭게 바꾸었고, 개행도 올바르게 맞추었습니다. 
- 새로고침이 발생하여도 redux의 내용이 증발하지 않도록 해주는 외부 라이브러리가 존재하지만, 최대한 외부라이브러리 사용을 배제하고자 하였고, 그 결과 구조상 액션함수가 이전보다 비교적 많이 실행된다는 단점이 있습니다. 
- 스타일적으로 문제가 되는 부분이 있는지 확인이 필요합니다.  
- 프로그램 구조에 관하여 좀 더 생각하는 시간이 있으면 좋을 것 같습니다.

새로고침 시 로그인 풀리는 문제점 해결 및 약간의 스타일 수정

---

package-lock.json
src/App.js
src/components/Layout.js
src/components/Menu.js
src/components/Menu.scss
src/index.scss
src/pages/Home.js

- sidebar를 추가하려다보니 전체적인 구조를 바꿀 수 밖에 없는 상황이었습니다. 
- 로그인/아웃 버튼은 메인페이지에 있기보단 사이드메뉴에 있는 것이 좋을 것 같아 옮기게되었습니다.
- 우선 App.js에 작성했던 Route는 `./components/Layout.js` 이쪽으로 옮겼습니다. 이제 여기서 라우트를 나눠주면 됩니다.
- Layout.js에는 2개의 영역이 있습니다. 하나는 `<Menu /> `다른 하나는 보여줄 페이지 들입니다. 이 2개의 비율이 1:4입니다.
- 해당 메뉴버튼을 눌렀을 때 그 해당 페이지를 누르고 있는 효과를 넣어보려고 합니다.  
- 디자인이 아직 많이 부족합니다.
- classname 혹은 전체적인 구조에 문제가 있다면 피드백 부탁드립니다.

App전체적인 구조 변경(sidebar: content = 1:4 의 비율) sidebar에 메뉴 추가, 기존의 로그인/아웃버튼 이동

---

package-lock.json
package.json
public/index.html
src/ModalPortal.js
src/components/Button.js
src/components/Button.scss
src/components/Menu.js
src/components/Menu.scss
src/components/Modal.js
src/components/Modal.scss
src/components/Topbar.js
src/components/Topbar.scss
src/pages/Home.js
src/pages/Home.scss

- 앱 내 css 디자인을 수정했습니다.
- 재사용성 가능한 (포탈)창 구현했습니다.
- `@mui/material` 다시 설치하였습니다.
- 모달창(재사용가능)
- Topbar의 버튼 css 수정, Sidebar의 `Link` tag 범위 조정
- 필요없는 코드 제거
- 프롭스 수정(button,modal)
- 메인 로고 누를시 홈페이지로 이동
- css파일이 많아지면서 관리하기가 조금씩 힘들어집니다. 관리하는 방법이 있을 것 같은데 계속해서 팀원들간 조사해보겠습니다.
- 클래스네임, 구현한 로직에 문제가 있으면 피드백 부탁드립니다! 버튼의 onclick 이벤트 내 함수들 통일성을 유지해야할 것 같은데 의견 부탁립니다!

Modal Portal구현, 메인페이지 언어 고를시 연습모드 고르는 Modal 등장, Sidebar Link태그 범위 수정, 마이페이지, 로그인버튼 디자인 수정

---

package-lock.json
src/App.js
src/api/index.js
src/components/Layout.js
src/features/userSaga.js
src/features/userSlice.js
src/pages/UserPage.js
src/store/index.js

- 마이 페이지 화면을 구현하기 위해 코드를 작성하였음
- 디자인 라이브러리의 원활한 실행을 위해 해당 라이브러리를 설치할 필요가 있었음
- 충돌 문제 해결
- 마이페이지로 이동하는 라우팅 경로를 추가하였음
- 마이페이지 화면 자체에서 보여지는 유저의 정보는 서버에게 get 요청을 보내 유저 정보를 가져오는 것이 아니라, redux에 저장된 유저 정보를 가져올 수 있도록 하였음.  
- 따라서 redux는 기존보다 더 많은 유저정보를 상태관리해야 할 필요성이 있었고, 따라서 redux가 관리하는 상태의 개수를 증가시켰음
- 마이페이지에서는 유저가 환경설정을 조작하는 부분도 들어있음. 유저가 환경설정을 변경할 경우 우선 변경된 정보가 redux에 반영되며, 또한 saga 함수가 이를 감지하여 DB에 있는 유저 정보도 update 될 수 있도록 구현하였음.
- 유저페이지에는 지난날의 기록들도 보여줄 수 있어야 하는데, 아직 기록 정보는 DB에 반영되어있지 않기 때문에 이 부분은 아직 제대로 실행되지 않음
- 유저 정보를 불러올 때, 그리고 이것이 변경이 될 때 redux 및 saga 함수 로직이 어떻게 흘러가는지를 자세히 봐주시면 감사하겠습니다.

마이페이지 화면 구현 & git 충돌 fix 

---

package-lock.json
package.json
src/components/Menu.js
src/components/Topbar.js

- material 라이브러리 제거 => react icons 설치
-  material 라이브러리의 icon만 사용하기에는 너무 과하다고 생각이들었고, 원하는 디자인이 많이 없었습니다.
- 없습니다.
- 없습니다.

design: 리액트아이콘으로 아이콘 디자인 변경, 기존의 material 제거

---

src/components/Topbar.js
src/pages/PracticePage.js
src/pages/UserPage.js

- 이전까지는 로그인하지 않은 상태에서 마이페이지 보기 및 연습 수행이 가능하였는데, 로그인 하지 않을 경우 이를 제한할 필요성이 필요했음
- redux에서 로그인 했는지의 상태를 가져와서, 그 상태에 따라 컴포넌트의 구성이 달라지도록 구현하였음
- 로그인 한 경우 top bar에서 마이페이지 및 로그아웃 버튼이 세로로 정렬됨. 이를 고치기 위해 css 수정이 필요함.
- 로그인 안내 페이지를 기본적인 틀로만 작성하였는데 이 역시 디자인을 꾸밀 필요성이 있음
- 어떻게 css 디자인을 바꿔야할지도 같이 생각해서 봐주시면 감사하겠습니다.

로그인 하지 않은 경우 기능 수행을 제한하고, 로그인 안내가 뜨도록 변경

---

src/components/Menu.js
src/pages/PracticePage.js
src/pages/UserPage.js

- 버그를 발견하여 이를 해결하고자 코드를 작성하였음.
- 로그인 하지 않은 상태에서는 좌측 사이드바에 로그인을 해달하는 문구를 뜨게 하여, 기존에 문제 페이지로 넘어갈 수 있었던 버그를 수정하였음
- 로그인 하지 않은 상태에서 서버에게 문제 정보를 가져오는 get 요청을 보내지 않도록 버그 수정
- 더이상 사용하지 않거나 존재하지 않는 변수를 불러오지 않도록 함. 
- 없음
-

로그아웃 상태에서의 버그 발생 이슈 해결 

---

src/features/problemsSlice.js
src/pages/PracticePage.js
src/pages/WordPracticePage.js
src/pages/WordPracticePage.module.scss
src/store/index.js

- 타자를 치다가 새로고침이 일어나면, 다시 문제들을 못불러오는 상황이발생! 그 이유는 이전페이지에서 서버요청으로 데이터들을 불러왔는데, 연슴 페이지가 달라지면서 요청을 다시 불러오지 못하는 상황이 발생하는 것이었음. (useEffect가 이전페이지에 있음) 
- 따라서, 이전페이지에서 바로 리덕스 스토어에 저장을 시켜주어 전역적으로 데이터를 관리하기로 하였습니다.
- problemsSlice추가
- 
- 로직이나 변수명 한번씩 봐주시면 감사하겠습니다.

feat: problems 데이터 리덕스 스토어에 상태 저장

---

package-lock.json
package.json
src/App.js
src/components/Spinner.js
src/components/Topbar.js
src/features/userSaga.js
src/features/userSlice.js
src/store/index.js

- 새로고침 발생 시 새로고침 과정이 진행중이거나 완료되었다는 상태를 만들 필요성이 있었음.
- 새로고침 진행 도중 유저가 로그인 버튼을 누르거나, 다른 조작을 하지 못하게 막을 필요성이 있었음
- 새로고침과 관련한 리덕스 액션 함수 및 사가 함수를 만들었음
- 스피너를 새롭게 추가하여 유저가 불러오고 있는 과정을 체감할 수 있게 하였음
- 없음
-

Feat/spinner 및 새로고침과 관련된 redux 액션함수 구현

---

src/App.scss
src/components/Button.scss
src/components/Keyboard.js
src/components/Keyboard.module.scss
src/components/Menu.js
src/components/Menu.module.scss
src/components/Modal.scss
src/components/Spinner.js
src/components/Topbar.module.scss
src/pages/WordPracticePage.module.scss

- 키보드 자판을 칠 때, 한글과 좌우상하 방향키를 입력하면 오류메세지가 발생(키코드 조건을 안걸어줘서 그랬습니다.) 
- 우측 shift키 자판을 칠 때 활성화되지 않아, location이라는 조건을 걸어주어 활성화되게 하였습니다.
- 기타css작업
- 전체적인 레이아웃모습과 색깔, 키보드 기능 수정
- edge case 발견되면 피드백 부탁드립니다.
- 없습니다. 오늘도 화이팅입니다 유체이탈팀 :)

refactor: keyboard자판 로직 수정 및 약간의 CSS수정

---

src/App.scss
src/pages/SentencePracticePage.js
src/pages/UserPage.js
src/pages/UserPage.module.scss
src/pages/WordPracticePage.js
src/pages/WordPracticePage.module.scss

- 다음 작업 충돌 방지를(tag와 추가하는 것들) 위해서 우선 css 작업하던 것을 먼저 PR요청드립니다.
- css구조만 바뀌었습니다. (tag, 위치)
- 없습니다.
-  없습니다.

design: word연습페이지, 유저페이지 전체적인 구조 수정

---

src/App.scss
src/components/Keyboard.js
src/pages/UserPage.js
src/pages/UserPage.module.scss
src/pages/WordPracticePage.js
src/pages/WordPracticePage.module.scss
src/utils/getCharacterClass.js

- 연습이 끝나고 모달창을 띄어줘도 키보드가 눌리고 소리가 나는 것을 수정했습니다. 
- 숫자패드와 esc버튼을 누를 때 오류가 생기던 것을 조건을 추가하여 막아주었습니다. 
- 유저페이지 기본적인 모양이 바뀌었습니다.
- 현재 유저페이지 기록을 보여주는 칸이 추후에 기록이 많아지면 스크롤이 엄청 길게 생길 것 같습니다. 현재 이 문제점을 보완해야할 것 같네요.
- 단어의 현재 위치를 표시해주는 로직이 현재 불완정합니다. 피드백 부탁드립니다.

feat: 연습이 끝나면 키보드 소리, 시각화 차단 및 기타 키보드 자판 누를시 에러발생되는 요소 차단, 유저페이지 구조, 현재 단어의 위치를 표시해주는 기능 작업 중 

---

package-lock.json
package.json
src/features/problemSaga.js
src/features/problemSlice.js
src/main.js
src/pages/ParagraphPracticePage.js
src/pages/SentencePracticePage.js
src/pages/UserPage.js
src/pages/WordPracticePage.js

- electron을 통해 데스크톱 앱을 만들기 위해 이를 설치할 필요성이 있었음
- 백엔드로부터 전달받는 연습문제 데이터가 변경되었으므로 이를 다시 맟출 필요가 있었음
- npm start를 할 경우 electron 모듈이 실행되도록 변경함
- redux 및 saga 함수 로직 개편
- 없음
- electron 실행 창의 크기 및 디자인에 대해 다시 논의해야 할 것 같습니다.

Feat/electron 추가 및 redux 구조 리펙토링

---

src/App.scss
src/components/Button.scss
src/components/Menu.module.scss
src/components/Modal.scss
src/components/Topbar.module.scss
src/pages/Home.js
src/pages/Home.module.scss
src/pages/SentencePracticePage.js
src/pages/UserPage.js
src/pages/UserPage.module.scss
src/pages/WordPracticePage.js
src/pages/WordPracticePage.module.scss

- 짧은 글 디자인 추가, 결과 나올 시 키보드 작동 금지, 전체적인 디자인 수정
- 짧은 글에도 타이핑 하고 있는 위치와 소리 추가, 결과 모달창 뜰 시 키보드 작동 금지 추가
- 현재 로직이 조금 부족한 면이 있어 틀린 소리 재생을 어느 부분에 넣어줘야할 지 고민 중입니다.
- 전체적인 피드백과 소리 재생관련 한번씩 의견 부탁드리겠습니다.

feat: 짧은 글 연습 현재 커서 추가, 결과 나올 시 키보드 작동 금지, 디자인 수정

---

package-lock.json
package.json
public/electron.js
src/components/Topbar.js
src/features/userSaga.js
src/features/userSlice.js
src/index.js
src/pages/ParagraphPracticePage.js
src/pages/SentencePracticePage.js
src/store/index.js

- electron 배포를 위한 세팅을 마칠 필요가 있었습니다. 
- 익명 로그인 기능을 추가할 필요가 있었습니다.
- electron 배포를 위한 세팅 옵션을 추가하였고, 관련 라이브러리를 설치하였습니다. 
- 익명 로그인 기능을 구현하였습니다. 이를 위해 상단바에 버튼을 추가하였고, 익명 로그인 여부 상태를 관리하는 redux 로직을 추가하였습니다.
- 또 익명 로그인을 할 경우 게임 결과를 서버에 저장하지 않도록 각 게임 별 dispatch 로직을 수정하였습니다. 
- 없음
- 없음

Feat/electron 수정 및 익명 로그인 기능 구현 

---

package-lock.json
src/App.scss
src/components/Menu.js
src/components/Menu.module.scss
src/components/Topbar.js

- 전체적인 디자인 수정 및 배포 자동화 여부 테스트 중입니다. 
- 디자인 조금 변경되었습니다. 
- 없음
- 없음

design: 상단바 버튼 위치 조정, 메뉴 디자인 변경, 짧은 글 문제 보이는 곳 넓이 수정

---

package-lock.json
package.json
src/components/test/ParagraphPracticePage.test.js
src/pages/ParagraphPracticePage.js
src/test-utils.js

- firebase를 테스트하기위해서 firebase-mock 이라는 패키지를 설치했습니다.
- 우선 테스트 케이스의 기본 틀만 만들어 ParagraphPracticePage가 렌더링이 잘 되는지 테스트를 해보았습니다.
- redux-toolkit을 사용하였으므로 그에 맞는 공식홈페이지에 나와있는 Writing Tests에 따라 테스트케이스에서 redux에서 관리하는 부분들을 잘 불러올 수 있도록 하기 위해 작성한 코드입니다.
- 주석처리한 부분은 필요한 것 같아서 사용중이므로 주석처리로 같이 PR에 올렸습니다.
- ParagraphPracticePage 에서 Keyboard 컴포넌트를 삭제하였고 소리기능은 그대로 유지 될 수 있도록 코드를 구현하였습니다.
- 없습니다.
- test 폴더 구조 및 로직에 문제점이 있으면 리뷰 부탁드립니다.

firebase-mock 설치, ParagraphPracticePage 테스트 코드 작성 및 키보드 UI 컴포넌트 제거, 소리기능은 유지하기 위한 코드 작성

---

src/mock/paragraphs.json
src/mock/sentences.json
src/mock/words.json
src/pages/PracticePage.js
src/utils/loadMockData.js

- 완전한 오프라인 환경에서 electron이 문제를 불러오지 못하는 경우를 해결하기 위함입니다.
- 오프라인인 환경인경우(즉 게스트 로그인 상태인 경우) 문제가 담겨있는 mockdata에서 문제를 불러오도록 구현하였습니다.
- 없음
- 없음

Fix/완전한 오프라인 환경에서 electron 문제 불러오지 못하는 버그 수정

---

.eslintrc.json
package-lock.json
package.json
src/components/test/Home.test.js
src/components/test/ParagraphPracticePage.test.js
src/components/test/UserPage.test.js
src/components/test/WordPracticePage.test.js
src/components/test/mock/ProblemSliceMock.js
src/components/test/mock/UserSliceMock.js
src/pages/Home.js
src/pages/UserPage.js
src/pages/WordPracticePage.js
src/utils/renderTest.js

- 기본적인 프론트엔드 유닛테스트를 작성해보았습니다.
- 리덕스 목업 슬라이스를 사용한 renderTest 유틸함수가 추가되었습니다. firebase mock을 사용하지 않고 slice의 목업 데이터를 사용하여 테스트를 진행하였습니다.
- firebase mock을 통해 로그인 테스트 등 여러가지를 진행해보고 싶었는데, 아직 제대로 된 방법을 찾지 못하였습니다. 
- 좀 더 추가했으면 하는 테스트, 다른 여러 테스트들을 팀원들과 더 상의해보겠습니다. 변수명, 파일이름 등 피드백 부탁드립니다.

test: frontend unit test 작성

---

src/components/test/mock/problemSliceMock.js
src/components/test/mock/userSliceMock.js

- 파일명을 대문자에서 소문자로 변경하였는데 git에서 설정을 해주지 않으면 수정된 부분이 반영이 되지 않는 다는 것을 알게 되었고, `git config core.ignorecase false` 나 `git mv oldName newName`를 통해 대소문자 구분을 할 수 있도록 설정을 해주어야합니다.
- ProblemSliceMock.js -> problemSliceMock.js
- UserSliceMock.js ->  userSliceMock.js 
- 없습니다.
- 없습니다.

problemSliceMock.js 및 userSliceMock.js 소문자변경 버그 수정
